import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SB_URL=Deno.env.get("SUPABASE_URL")!;
const SB_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"GET, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const fallback=["celular","fone bluetooth","smartwatch","air fryer","aspirador","cafeteira"];
const enc=new TextEncoder();
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors})}
function ub64u(v:string){const s=atob(v.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-v.length%4)%4));return Uint8Array.from(s,c=>c.charCodeAt(0))}
async function aesKey(){const raw=await crypto.subtle.digest("SHA-256",enc.encode(`${SB_KEY}:oauth-token-v1`));return crypto.subtle.importKey("raw",raw,"AES-GCM",false,["decrypt"])}
async function openSecret(v:string|null){if(!v)return null;const [ivS,ctS]=v.split(".");if(!ivS||!ctS)return null;const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:ub64u(ivS)},await aesKey(),ub64u(ctS));return new TextDecoder().decode(plain)}
async function accessToken(){const s=createClient(SB_URL,SB_KEY,{auth:{persistSession:false}});const {data,error}=await s.from("oauth_connections").select("access_token_enc,updated_at").eq("provider","mercadolivre").order("updated_at",{ascending:false}).limit(1);if(error)throw error;return openSecret(data?.[0]?.access_token_enc??null)}
function level(score:number){return score>=75?"Alta":score>=55?"Média":"Baixa"}
function scoreItem(item:any,rank:number){const sold=Number(item.sold_quantity??0);const price=Number(item.price??0);const original=Number(item.original_price??0);const discount=original>price&&original>0?((original-price)/original)*100:0;const trend=Math.max(0,35-rank*4);const sales=Math.min(35,Math.log10(sold+1)*10);const discountPts=Math.min(15,discount*.5);const shipping=item.shipping?.free_shipping?8:0;const official=item.official_store_id?7:0;const stock=Number(item.available_quantity??0)>0?5:0;return Math.max(0,Math.min(100,Math.round(trend+sales+discountPts+shipping+official+stock)))}
async function meliFetch(url:string,token:string|null){const headers:Record<string,string>={accept:"application/json"};if(token)headers.Authorization=`Bearer ${token}`;return fetch(url,{headers})}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});try{const token=await accessToken();const url=new URL(req.url);const custom=(url.searchParams.get("q")||"").trim();let terms:string[]=[];let source="trends";
if(custom){terms=[custom];source="search"}else{try{const tr=await meliFetch("https://api.mercadolibre.com/trends/MLB",token);if(tr.ok){const data=await tr.json();terms=(Array.isArray(data)?data:[]).slice(0,6).map((x:any)=>String(x.keyword||"").trim()).filter(Boolean)}}catch{}if(!terms.length){terms=fallback;source="fallback"}}
const diagnostics:any[]=[];
const batches=await Promise.all(terms.map(async(term,rank)=>{try{const s=new URL("https://api.mercadolibre.com/sites/MLB/search");s.searchParams.set("q",term);s.searchParams.set("limit","12");const r=await meliFetch(s.toString(),token);if(!r.ok){diagnostics.push({term,status:r.status});return []}const d=await r.json();const results=Array.isArray(d.results)?d.results:[];diagnostics.push({term,status:r.status,count:results.length});return results.map((item:any)=>({id:item.id,title:item.title,price:item.price,original_price:item.original_price??null,currency_id:item.currency_id||"BRL",thumbnail:item.thumbnail?.replace("http://","https://")||null,permalink:item.permalink,sold_quantity:item.sold_quantity??0,available_quantity:item.available_quantity??0,free_shipping:!!item.shipping?.free_shipping,official_store:!!item.official_store_id,trend_term:term,score:scoreItem(item,rank)}))}catch(e){diagnostics.push({term,error:e instanceof Error?e.message:"fetch_error"});return []}}));
const dedup=new Map<string,any>();for(const item of batches.flat()){const prev=dedup.get(item.id);if(!prev||item.score>prev.score)dedup.set(item.id,item)}const products=[...dedup.values()].sort((a,b)=>b.score-a.score||b.sold_quantity-a.sold_quantity).slice(0,30).map((x:any)=>({...x,opportunity:level(x.score)}));return json({ok:true,source,authenticated:!!token,terms,generated_at:new Date().toISOString(),count:products.length,products,diagnostics})}catch(e){console.error(e instanceof Error?e.message:"meli_hot_products_error");return json({ok:false,error:"internal_error"},500)}});