import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SB_URL = Deno.env.get("SUPABASE_URL")!;
const SB_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const CLIENT_ID = Deno.env.get("MELI_CLIENT_ID")!;
const CLIENT_SECRET = Deno.env.get("MELI_CLIENT_SECRET")!;
const enc = new TextEncoder();
const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"GET, OPTIONS","Content-Type":"application/json; charset=utf-8"};
function ub64u(v:string){const s=atob(v.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-v.length%4)%4));return Uint8Array.from(s,c=>c.charCodeAt(0))}
function b64u(a:Uint8Array){let s="";for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function aesKey(){const raw=await crypto.subtle.digest("SHA-256",enc.encode(`${SB_KEY}:oauth-token-v1`));return crypto.subtle.importKey("raw",raw,"AES-GCM",false,["encrypt","decrypt"])}
async function openSecret(v:string|null){if(!v)return null;const [ivS,ctS]=v.split(".");if(!ivS||!ctS)return null;const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:ub64u(ivS)},await aesKey(),ub64u(ctS));return new TextDecoder().decode(plain)}
async function seal(v?:string|null){if(!v)return null;const iv=crypto.getRandomValues(new Uint8Array(12));const ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},await aesKey(),enc.encode(v)));return `${b64u(iv)}.${b64u(ct)}`}
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors})}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});try{const s=createClient(SB_URL,SB_KEY,{auth:{persistSession:false}});const {data,error}=await s.from("oauth_connections").select("external_account_id,access_token_enc,refresh_token_enc,expires_at,updated_at").eq("provider","mercadolivre").order("updated_at",{ascending:false}).limit(1);if(error)throw error;const row=data?.[0];if(!row)return json({connected:false,reason:"not_connected"},404);let token=await openSecret(row.access_token_enc);const refresh=await openSecret(row.refresh_token_enc);if(!token)return json({connected:false,reason:"missing_token"},500);const exp=row.expires_at?new Date(row.expires_at).getTime():0;if(exp&&exp<Date.now()+5*60_000&&refresh&&CLIENT_ID&&CLIENT_SECRET){const body=new URLSearchParams({grant_type:"refresh_token",client_id:CLIENT_ID,client_secret:CLIENT_SECRET,refresh_token:refresh});const rr=await fetch("https://api.mercadolibre.com/oauth/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded","accept":"application/json"},body});const rt=await rr.json();if(rr.ok&&rt.access_token){token=rt.access_token;const ttl=Number(rt.expires_in??0);await s.from("oauth_connections").update({access_token_enc:await seal(rt.access_token),refresh_token_enc:await seal(rt.refresh_token??refresh),expires_at:ttl?new Date(Date.now()+ttl*1000).toISOString():row.expires_at,updated_at:new Date().toISOString()}).eq("provider","mercadolivre").eq("external_account_id",row.external_account_id)}}const r=await fetch("https://api.mercadolibre.com/users/me",{headers:{Authorization:`Bearer ${token}`}});const me=await r.json();if(!r.ok)return json({connected:false,reason:"api_error",status:r.status},502);return json({connected:true,provider:"mercadolivre",user:{id:me.id,nickname:me.nickname,site_id:me.site_id,status:me.status},last_sync:new Date().toISOString()});}catch(e){console.error(e instanceof Error?e.message:"meli_status_error");return json({connected:false,reason:"internal_error"},500)}});