create table if not exists public.oauth_connections (
  id bigint generated by default as identity primary key,
  provider text not null,
  external_account_id text not null default 'default',
  access_token_enc text,
  refresh_token_enc text,
  token_type text,
  scope text,
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, external_account_id)
);

alter table public.oauth_connections enable row level security;
revoke all on table public.oauth_connections from anon, authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists oauth_connections_set_updated_at on public.oauth_connections;
create trigger oauth_connections_set_updated_at
before update on public.oauth_connections
for each row execute function public.set_updated_at();
